version: '3'

services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
    networks:
    - postgres

  test-db:
    container_name: postgres_test_db
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: pass123
    networks:
    - postgres

  pgadmin:
    links:
    - db:postgres_db
    - db:postgres_test_db
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - '8080:80'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
    - postgres

networks:
  postgres:
    driver: bridge
